#!/bin/sh
#
# mkshrc

if ! command -v pfetch >/dev/null; then pfetch() { :; }; fi

pfetch

COL0='\x1b[0;30m'
COL1='\x1b[0;31m'
COL2='\x1b[0;32m'
COL3='\x1b[0;33m'
COL4='\x1b[0;34m'
COL5='\x1b[0;35m'
COL6='\x1b[0;36m'
COL7='\x1b[0;37m'
COL8='\x1b[1;30m'
COL9='\x1b[1;31m'
COL10='\x1b[1;32m'
COL11='\x1b[1;33m'
COL12='\x1b[1;34m'
COL13='\x1b[1;35m'
COL14='\x1b[1;36m'
COL15='\x1b[1;37m'
BOLD='\x1b[1m'
NORMAL='\x1b[0m'

# prompt
# bashism required b/c mksh doesn't support param expansion for PS1
PS1=$'$(printf '%b' "${COL10}${PWD} $ ${NORMAL}")'
export PS1

# gpg tty
GPG_TTY="$(tty)"
export GPG_TTY

# aliasrc
[ -f "${XDG_CONFIG_HOME:-${HOME}/.config}/sh/aliasrc" ] && . "${XDG_CONFIG_HOME:-${HOME}/.config}/sh/aliasrc"

# functionrc
[ -f "${XDG_CONFIG_HOME:-${HOME}/.config}/sh/functionrc" ] && . "${XDG_CONFIG_HOME:-${HOME}/.config}/sh/functionrc"
