#!/bin/sh
#
# aliasrc

# posix
alias \
    bc='bc -l'        \
    cp='cp -R'        \
    ls='ls -ls'       \
    mkdir='mkdir -p'  \
    more='less'       \
    rm='rm -iR'       \
    rmdir='rmdir -p'

# gnu/linux
if uname -s | grep -i 'linux' >/dev/null 2>&1; then
    alias \
         bc='bc -lq'                                          \
         cp='cp -vR'     					                  \
         def='sdcv -u '\''en-wiktionary'\'''                  \
         df='df -hT'     					                  \
         diff='diff --color=auto'                             \
         du='du -h'                  			              \
         echo='echo -en'             			              \
         egrep='egrep --color=auto'			                  \
         fgrep='fgrep --color=auto'			                  \
         ft='grep -inwIR'                                     \
         grep='grep --color=auto'                             \
         ls='ls -ahls --color=auto --group-directories-first' \
         mv='mv -v'                 			              \
         o='open.sh'                                          \
         paru='paru --sudo doas'                              \
         rmdir='rmdir -pv --ignore-fail-on-non-empty'         \
         vi='vim'                                             \
         vm='qemu-system-x86_64                               \
             -cpu host                                        \
             -enable-kvm                                      \
             -k de                                            \
             -m 4096                                          \
             -machine type=pc,accel=kvm                       \
             -net nic                                         \
             -net user,hostfwd=tcp::10022-:22                 \
             -smp $(nproc)                                    \
             -soundhw all                                     \
             -usb                                             \
             -vga std'

fi

# directories
alias \
     ...='cd ../../'             \
     ....='cd ../../../'         \
     .....='cd ../../../../'     \
     ......='cd ../../../../../'

# git
alias \
     ga='git add'                  \
     gb='git branch'               \
     gba='git branch -a'           \
     gbv='git branch -v'           \
     gca='git commit --amend'      \
     gch='git checkout'            \
     gcm='git commit -m'           \
     gd='git diff'                 \
     gdc='git diff --cached'       \
     gf='git fetch'                \
     gp='git push'                 \
     gpl='git pull'                \
     gplo='git pull origin'        \
     gpo='git push origin'         \
     gpom='git push origin master' \
     gr='git rebase'               \
     gs='git status'               \
     gst='git stash'               \
     gsta='git stash apply'        \
     gstc='git stash clear'        \
     gstl='git stash list'         \
     gstp='git stash pop'

# dots
alias dots='/usr/bin/git --git-dir=${HOME}/.dots/ --work-tree=${HOME}'

# sync mail on mail exit when entered thru cmd line
alias ${MAIL_CLIENT}='"${HOME}/.local/bin/bar/mail.sh" -o'

# youtube
# NOTE: since 03 december 2021, youtube-dl should be a symlink to yt-dlp
#       youtube-dl seems to be dead (last commit 01 july 2021) and there are unresolved issues (e.g., bandwidth throttling)
#       yt-dlp is a fork of youtube-dl and seems to be a perfect stand-in for most use cases
#       all programs that rely on youtube-dl should work
#       https://github.com/yt-dlp/yt-dlp
alias \
    yt='youtube-dl -i -o "${DOWNLOADS_DIR}/%(uploader)s/%(title)s.%(ext)s" --add-metadata'                     \
    yta='yt -f bestaudio/best -x'                                                                              \
    ytp='youtube-dl -i -o "${DOWNLOADS_DIR}/%(uploader)s/%(playlist_index)s-%(title)s.%(ext)s" --add-metadata' \
    ytpa='ytp -f bestaudio/best -x'                                                                            \
    ytall='yt -cw -f best'                                                                                     \
    ytw='${YOUTUBE_CLIENT}'
