#!/bin/sh
#
# profile

# add local scripts to path
PATH="${PATH}:$(du "${HOME}/.local/bin/" | cut -f2 | tr '\n' ':' | sed 's/:*$//')"
export PATH

# programs
export WM='dwm'
export BAR='dwmblocks'
export MENU='dmenu_run -c -l 10'
export LOCKER='slock'
export BROWSER='firefox'
export TERMINAL='st'
export FILE_VIEWER='fff'
export EDITOR='vim'
export MUSIC_PLAYER='cmus'
export MAIL_CLIENT='neomutt'
export MEDIA_PLAYER='mpv'
export READER='zathura'
export IMG_VIEWER='feh'

# xdg base directories
export XDG_CONFIG_HOME="${HOME}/.config/"
export XDG_DATA_HOME="${HOME}/.local/share/"
export XDG_CACHE_HOME="${HOME}/.cache/"
export XDG_STATE_HOME="${HOME}/.local/state/"

# xdg base directory support
export VIMINIT="source ${XDG_CONFIG_HOME:-${HOME}/.config}/vim/vimrc"
export GNUPGHOME="${XDG_DATA_HOME:-${HOME}/.local/share}/gnupg/"
export ENV="${XDG_CONFIG_HOME:-${HOME}/.config}/mksh/mkshrc"
export HISTFILE=''
export XAUTHORITY="${XDG_RUNTIME_DIR}/xauth"

# folders
export DEV_DIR="${HOME}/dev/"
export DOWNLOADS_DIR="${HOME}/dl/"
export DOCUMENTS_DIR="${HOME}/dox/"
export MAIL_DIR="${HOME}/mail/"
export MUSIC_DIR="${HOME}/music/"
export PICTURES_DIR="${HOME}/pix/"
export VIDEOS_DIR="${HOME}/vids/"

# gpg
export GNUPG="9CC4E75365C16465FFE752C94DDBF97211D4EA31"

# colorful man pages
LESS_TERMCAP_mb="$(printf '\e[01;31m')"
export LESS_TERMCAP_mb
LESS_TERMCAP_md="$(printf '\e[01;38;5;74m')"
export LESS_TERMCAP_md
LESS_TERMCAP_me="$(printf '\e[0m')"
export LESS_TERMCAP_me
LESS_TERMCAP_se="$(printf '\e[0m')"
export LESS_TERMCAP_se
LESS_TERMCAP_so="$(printf '\e[38;5;246m')"
export LESS_TERMCAP_so
LESS_TERMCAP_ue="$(printf '\e[0m')"
export LESS_TERMCAP_ue
LESS_TERMCAP_us="$(printf '\e[04;38;5;146m')"
export LESS_TERMCAP_us

# file explorer
export FFF_COL1=4
export FFF_COL2=4
export FFF_COL3=1
export FFF_COL4=4
export FFF_COL5=6
export FFF_HIDDEN=1
export FFF_LS_COLORS=1
export FFF_OPENER="xdg-open"
export FFF_STAT_CMD="stat"

# pash
export PASH_KEYID="${GNUPG}"
export PASH_LENGTH=32
export PASH_PATTERN=_A-Z-a-z-0-9
export PASH_DIR="${XDG_DATA_HOME:-${HOME}/.local/share}/pash/"
export PASH_CLIP='xclip -sel c'
export PASH_TIMEOUT=60

# pfetch
export HOSTNAME='pc'
export PF_INFO='ascii title os host kernel uptime pkgs memory shell editor wm palette'
export PF_COL1=4

# clean up
export LESSHISTFILE=-

# sx
[ -z "${DISPLAY}" ] && [ "$(tty)" = /dev/tty1 ] && ssh-agent sx
