#!/bin/sh
#
# profile

# add local scripts to path
PATH="${PATH}:$(du "${HOME}/.local/bin/" | cut -f 2 | tr '\n' ':' | sed 's/:*$//')"
export PATH

# programs
export WM='dwm'
export BAR='dwmblocks'
export MENU='dmenu_run -c -l 10'
export LOCKER='slock'
export BROWSER='brave'
export TERMINAL='st'
export FILE_VIEWER='fff'
export EDITOR='vim'
export MAIL_CLIENT='neomutt'
export MUSIC_PLAYER='ncmpcpp'
export READER='zathura'
export YOUTUBE_CLIENT='ytfzf'
export IMG_VIEWER='feh'
export MIXER='alsamixer'
export TORRENT_CLIENT='deluge-gtk'
export IMAGE_EDITOR='gimp-2.99'

# xdg base directories
export XDG_CONFIG_HOME="${HOME}/.config/"
export XDG_DATA_HOME="${HOME}/.local/share/"
export XDG_CACHE_HOME="${HOME}/.cache/"
export XDG_STATE_HOME="${HOME}/.local/state/"

# xdg base directory support
export VIMINIT="source ${XDG_CONFIG_HOME:-${HOME}/.config/}/vim/vimrc"
export GNUPGHOME="${XDG_DATA_HOME:-${HOME}/.local/share/}/gnupg/"
export ENV="${XDG_CONFIG_HOME:-${HOME}/.config/}/mksh/mkshrc"
export HISTFILE=''
export XAUTHORITY="${XDG_RUNTIME_DIR}/xauth"
export YTFZF_CONFIG_DIR="${XDG_CONFIG_HOME:-${HOME}/.config/}/ytfzf/"
export YTFZF_CONFIG_FILE="${YTFZF_CONFIG_DIR}/ytfzf.sh"
export STARDICT_DATA_DIR="${XDG_DATA_HOME:-${HOME}/.local/share/}"

# folders
export MAIL_DIR="${HOME}/mail/"
export PICTURES_DIR="${HOME}/pix/"
export DOWNLOADS_DIR="${HOME}/dl/"

# colorful man pages
LESS_TERMCAP_mb="$(printf '%b' '\x1b[1;32m')"
export LESS_TERMCAP_mb
LESS_TERMCAP_md="$(printf '%b' '\x1b[1;32m')"
export LESS_TERMCAP_md
LESS_TERMCAP_me="$(printf '%b' '\x1b[0m')"
export LESS_TERMCAP_me
LESS_TERMCAP_so="$(printf '%b' '\x1b[1;30;42m')"
export LESS_TERMCAP_so
LESS_TERMCAP_se="$(printf '%b' '\x1b[23;0m')"
export LESS_TERMCAP_se
LESS_TERMCAP_us="$(printf '%b' '\x1b[4;1;32m')"
export LESS_TERMCAP_us
LESS_TERMCAP_ue="$(printf '%b' '\x1b[24;0m')"
export LESS_TERMCAP_ue
LESS_TERMCAP_mr="$(printf '%b' '\x1b[7m')"
export LESS_TERMCAP_mr
LESS_TERMCAP_mh="$(printf '%b' '\x1b[2m')"
export LESS_TERMCAP_mh
LESS_TERMCAP_ZN=$(tput ssubm)
export LESS_TERMCAP_ZN
LESS_TERMCAP_ZV=$(tput rsubm)
export LESS_TERMCAP_ZV
LESS_TERMCAP_ZO=$(tput ssupm)
export LESS_TERMCAP_ZO
LESS_TERMCAP_ZW=$(tput rsupm)
export LESS_TERMCAP_ZW

# file explorer
export FFF_COL1=2
export FFF_COL2=2
export FFF_COL3=1
export FFF_COL4=2
export FFF_COL5=0
export FFF_HIDDEN=1
export FFF_LS_COLORS=1
export FFF_OPENER="${HOME}/.local/bin/open.sh"
export FFF_STAT_CMD="stat"

# pfetch
export HOSTNAME='laptop'
export PF_INFO='ascii title os host kernel uptime pkgs memory shell editor wm palette'
export PF_COL1=2

# fzf
export FZF_DEFAULT_OPTS='
    --color fg:7
    --color preview-fg:2
    --color preview-bg:2
    --color hl:2
    --color fg+:0
    --color bg+:2
    --color gutter:2
    --color hl+:7
    --color info:2
    --color border:2
    --color prompt:2
    --color pointer:2
    --color marker:2
    --color spinner:2
    --color header:2
'
# clean up
export LESSHISTFILE=-
export SDCV_HISTFILE='/dev/null'

# sx
[ -z "${DISPLAY}" ] && [ "$(tty)" = /dev/tty1 ] && ssh-agent sx
