#!/bin/sh
#
# xprofile

xrdb "${XDG_CONFIG_HOME:-${HOME}/.config/}/x/xresources"
"${HOME}/.local/bin/lock.sh" &
feh --no-fehbg --bg-scale "${XDG_DATA_HOME:-${HOME}/.local/share/}/wp"
xclickroot -r "${HOME}/.local/bin/menu.sh" &
xcompmgr &
mpd &
unclutter &
xset r rate 250 50
